# Do not modify this file! It was generated by nixos-generate-config.
{ lib, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = [ "virtio_scsi" "ahci" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/90f12f7f-6d37-438d-84d0-88559c62c15f";
    fsType = "ext4";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/2189a41b-4762-414a-8e3d-a1e17828f8f3"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
